ethereum_rpc = "https://rpc.hoodi.ethpandaops.io/"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]
[traps.my_unique_trap]
path = "out/MyUniqueTrap.sol/MyUniqueTrap.json"
response_contract = "0xNEW_RESPONSE_ADDRESS_PLACEHOLDER"
response_function = "respondToYourAnomaly(string,uint256)"
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 3
block_sample_size = 10
private = true
whitelist = ["0xYOUR_EVM_ADDRESS_PLACEHOLDER"]
private_trap = true
address = "0xNEW_TRAP_ADDRESS_PLACEHOLDER"
